feat: adicionar função de redefinir senha do Usuário
romeuborges19/projeto_barberease pull request #27
Opened 2023-10-24 21:40 UTC by gabrielbdsm

Isso inclui:
- Formulário para enviar email para redefirir senha
- Formulário para nova senha
- Modelo de redefinir senha no banco de dados
- Views para processar envio de email para redifinir senha
- Views para processar nova senha
- Validações da nova senha

 On branch feature/redefnirSenha
 Changes to be committed:
	new file:   barberease/usuarios/EmitEmail.py
	modified:   barberease/usuarios/forms.py
	modified:   barberease/usuarios/migrations/0001_initial.py
	deleted:    barberease/usuarios/migrations/0002_alter_usuario_sobrenome.py
	new file:   barberease/usuarios/migrations/0002_senharedefinicao.py
	new file:   barberease/usuarios/migrations/0003_alter_senharedefinicao_data_criacao.py
	modified:   barberease/usuarios/models.py
	modified:   barberease/usuarios/templates/registration/login.html
	new file:   barberease/usuarios/templates/usuario_new_password.html
	new file:   barberease/usuarios/templates/usuario_redefinir_senha.html
	modified:   barberease/usuarios/urls.py
	modified:   barberease/usuarios/views.py

2023-10-26 13:44 UTC, ana-flav requested changes
alem dos comentários do models, antes de finalizar o seu trabalho lembre-se de dar o git pull origin develop para evitarmos muitos conflitos. de resto esta tudo ok

2023-10-26 13:44 UTC, ana-flav commented on barberease/usuarios/models.py
> +class SenhaRedefinicao(models.Model):
Gabriel, cada classe criada no models é uma tabela criada no banco, no processo de redefinição de senha não é preciso criar mais uma tabela. para alterar uma senha voce tem que usar o models do usuario na alteração. Peço que modifique isso na seu codigo. Segue um link para ajudar [https://www.tutorialspoint.com/how-to-change-password-of-users-in-django](https://www.tutorialspoint.com/how-to-change-password-of-users-in-django). Tente usar esse metodo ou procure desde que a senha tem hash e nao crie outra tabela no bd

2023-10-26 14:05 UTC, romeuborges19 requested changes
Realizar mudanças requisitadas.

2023-10-26 14:05 UTC, romeuborges19 commented on barberease/usuarios/forms.py
> +            user = SenhaRedefinicao.objects.get(email=email)
Usar o model Usuario ao invés de criar um novo model, para evitar mal uso do banco de dados.

2023-10-26 14:05 UTC, romeuborges19 commented on barberease/usuarios/forms.py
> +        token = secrets.token_urlsafe(32)
O Django tem funcionalidades de redefinição de senha que podem ser usadas para evitar a criação de um novo model no banco de dados. 

Seguem conteúdos sobre:
https://www.sjoerdlangkemper.nl/2016/04/07/djangos-reset-password-mechanism/
https://github.com/django/django/blob/main/django/contrib/auth/tokens.py#L8
https://docs.djangoproject.com/en/3.2/ref/settings/#password-reset-timeout

2023-11-20 12:41 UTC, romeuborges19 approved these changes
Top

2023-11-20 23:30 UTC, gabrielbdsm reviewed
alterações concluída

2023-11-21 21:32 UTC, ana-flav approved these changes

2023-11-22 01:55 UTC, Ana4Julia approved these changes

2023-11-22 01:57 UTC, merged